// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package org.apache.flink.smoke.generated2;

public final class CommandsOuterClass {
  private CommandsOuterClass() {}
  public static void registerAllExtensions(
      org.apache.flink.com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      org.apache.flink.com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (org.apache.flink.com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final org.apache.flink.com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_flink_statefun_e2e_smoke_SourceCommand_descriptor;
  static final 
    org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_flink_statefun_e2e_smoke_SourceCommand_fieldAccessorTable;
  static final org.apache.flink.com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_flink_statefun_e2e_smoke_Commands_descriptor;
  static final 
    org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_flink_statefun_e2e_smoke_Commands_fieldAccessorTable;
  static final org.apache.flink.com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_descriptor;
  static final 
    org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_flink_statefun_e2e_smoke_Command_fieldAccessorTable;
  static final org.apache.flink.com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_IncrementState_descriptor;
  static final 
    org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_flink_statefun_e2e_smoke_Command_IncrementState_fieldAccessorTable;
  static final org.apache.flink.com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_Send_descriptor;
  static final 
    org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_flink_statefun_e2e_smoke_Command_Send_fieldAccessorTable;
  static final org.apache.flink.com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_SendAfter_descriptor;
  static final 
    org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_flink_statefun_e2e_smoke_Command_SendAfter_fieldAccessorTable;
  static final org.apache.flink.com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_CancelSendAfter_descriptor;
  static final 
    org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_flink_statefun_e2e_smoke_Command_CancelSendAfter_fieldAccessorTable;
  static final org.apache.flink.com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_SendEgress_descriptor;
  static final 
    org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_flink_statefun_e2e_smoke_Command_SendEgress_fieldAccessorTable;
  static final org.apache.flink.com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_AsyncOperation_descriptor;
  static final 
    org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_flink_statefun_e2e_smoke_Command_AsyncOperation_fieldAccessorTable;
  static final org.apache.flink.com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_Verify_descriptor;
  static final 
    org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_flink_statefun_e2e_smoke_Command_Verify_fieldAccessorTable;
  static final org.apache.flink.com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_flink_statefun_e2e_smoke_VerificationResult_descriptor;
  static final 
    org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_flink_statefun_e2e_smoke_VerificationResult_fieldAccessorTable;

  public static org.apache.flink.com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  org.apache.flink.com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016commands.proto\022#org.apache.flink.state" +
      "fun.e2e.smoke\"`\n\rSourceCommand\022\016\n\006target" +
      "\030\001 \001(\005\022?\n\010commands\030\002 \001(\0132-.org.apache.fl" +
      "ink.statefun.e2e.smoke.Commands\"I\n\010Comma" +
      "nds\022=\n\007command\030\001 \003(\0132,.org.apache.flink." +
      "statefun.e2e.smoke.Command\"\374\007\n\007Command\022P" +
      "\n\tincrement\030\001 \001(\0132;.org.apache.flink.sta" +
      "tefun.e2e.smoke.Command.IncrementStateH\000" +
      "\022A\n\004send\030\002 \001(\01321.org.apache.flink.statef" +
      "un.e2e.smoke.Command.SendH\000\022L\n\nsend_afte" +
      "r\030\003 \001(\01326.org.apache.flink.statefun.e2e." +
      "smoke.Command.SendAfterH\000\022N\n\013send_egress" +
      "\030\004 \001(\01327.org.apache.flink.statefun.e2e.s" +
      "moke.Command.SendEgressH\000\022V\n\017async_opera" +
      "tion\030\005 \001(\0132;.org.apache.flink.statefun.e" +
      "2e.smoke.Command.AsyncOperationH\000\022E\n\006ver" +
      "ify\030\006 \001(\01323.org.apache.flink.statefun.e2" +
      "e.smoke.Command.VerifyH\000\022Y\n\021cancel_send_" +
      "after\030\007 \001(\0132<.org.apache.flink.statefun." +
      "e2e.smoke.Command.CancelSendAfterH\000\032\020\n\016I" +
      "ncrementState\032W\n\004Send\022\016\n\006target\030\001 \001(\005\022?\n" +
      "\010commands\030\002 \001(\0132-.org.apache.flink.state" +
      "fun.e2e.smoke.Commands\032x\n\tSendAfter\022\016\n\006t" +
      "arget\030\001 \001(\005\022?\n\010commands\030\002 \001(\0132-.org.apac" +
      "he.flink.statefun.e2e.smoke.Commands\022\032\n\022" +
      "cancellation_token\030\003 \001(\t\032=\n\017CancelSendAf" +
      "ter\022\016\n\006target\030\001 \001(\005\022\032\n\022cancellation_toke" +
      "n\030\002 \001(\t\032\014\n\nSendEgress\032k\n\016AsyncOperation\022" +
      "\017\n\007failure\030\001 \001(\010\022H\n\021resolved_commands\030\002 " +
      "\001(\0132-.org.apache.flink.statefun.e2e.smok" +
      "e.Commands\032\032\n\006Verify\022\020\n\010expected\030\001 \001(\003B\t" +
      "\n\007command\"B\n\022VerificationResult\022\n\n\002id\030\001 " +
      "\001(\005\022\020\n\010expected\030\002 \001(\003\022\016\n\006actual\030\003 \001(\003B1\n" +
      "-org.apache.flink.statefun.e2e.smoke.gen" +
      "eratedP\001b\006proto3"
    };
    org.apache.flink.com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new org.apache.flink.com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public org.apache.flink.com.google.protobuf.ExtensionRegistry assignDescriptors(
              org.apache.flink.com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    org.apache.flink.com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new org.apache.flink.com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_apache_flink_statefun_e2e_smoke_SourceCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_apache_flink_statefun_e2e_smoke_SourceCommand_fieldAccessorTable = new
      org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_flink_statefun_e2e_smoke_SourceCommand_descriptor,
        new String[] { "Target", "Commands", });
    internal_static_org_apache_flink_statefun_e2e_smoke_Commands_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_apache_flink_statefun_e2e_smoke_Commands_fieldAccessorTable = new
      org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_flink_statefun_e2e_smoke_Commands_descriptor,
        new String[] { "Command", });
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_fieldAccessorTable = new
      org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_flink_statefun_e2e_smoke_Command_descriptor,
        new String[] { "Increment", "Send", "SendAfter", "SendEgress", "AsyncOperation", "Verify", "CancelSendAfter", "Command", });
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_IncrementState_descriptor =
      internal_static_org_apache_flink_statefun_e2e_smoke_Command_descriptor.getNestedTypes().get(0);
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_IncrementState_fieldAccessorTable = new
      org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_flink_statefun_e2e_smoke_Command_IncrementState_descriptor,
        new String[] { });
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_Send_descriptor =
      internal_static_org_apache_flink_statefun_e2e_smoke_Command_descriptor.getNestedTypes().get(1);
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_Send_fieldAccessorTable = new
      org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_flink_statefun_e2e_smoke_Command_Send_descriptor,
        new String[] { "Target", "Commands", });
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_SendAfter_descriptor =
      internal_static_org_apache_flink_statefun_e2e_smoke_Command_descriptor.getNestedTypes().get(2);
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_SendAfter_fieldAccessorTable = new
      org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_flink_statefun_e2e_smoke_Command_SendAfter_descriptor,
        new String[] { "Target", "Commands", "CancellationToken", });
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_CancelSendAfter_descriptor =
      internal_static_org_apache_flink_statefun_e2e_smoke_Command_descriptor.getNestedTypes().get(3);
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_CancelSendAfter_fieldAccessorTable = new
      org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_flink_statefun_e2e_smoke_Command_CancelSendAfter_descriptor,
        new String[] { "Target", "CancellationToken", });
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_SendEgress_descriptor =
      internal_static_org_apache_flink_statefun_e2e_smoke_Command_descriptor.getNestedTypes().get(4);
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_SendEgress_fieldAccessorTable = new
      org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_flink_statefun_e2e_smoke_Command_SendEgress_descriptor,
        new String[] { });
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_AsyncOperation_descriptor =
      internal_static_org_apache_flink_statefun_e2e_smoke_Command_descriptor.getNestedTypes().get(5);
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_AsyncOperation_fieldAccessorTable = new
      org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_flink_statefun_e2e_smoke_Command_AsyncOperation_descriptor,
        new String[] { "Failure", "ResolvedCommands", });
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_Verify_descriptor =
      internal_static_org_apache_flink_statefun_e2e_smoke_Command_descriptor.getNestedTypes().get(6);
    internal_static_org_apache_flink_statefun_e2e_smoke_Command_Verify_fieldAccessorTable = new
      org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_flink_statefun_e2e_smoke_Command_Verify_descriptor,
        new String[] { "Expected", });
    internal_static_org_apache_flink_statefun_e2e_smoke_VerificationResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_apache_flink_statefun_e2e_smoke_VerificationResult_fieldAccessorTable = new
      org.apache.flink.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_flink_statefun_e2e_smoke_VerificationResult_descriptor,
        new String[] { "Id", "Expected", "Actual", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
